###
GET http://localhost:4006/odata/v4/school/Students

###
GET http://localhost:4006/odata/v4/school/Stud_Mark(student_id='1001',subject='English')

###
GET http://localhost:4006/odata/v4/school/Stud_Mark?$filter=student_id eq '1001'

###
POST http://localhost:4004/odata/v4/school/Students
Content-Type: application/json

 {
    "student_id": "1004",
    "student_name": "HIMABINDU"
}

###
GET http://localhost:4006/odata/v4/school/Students

###
PATCH http://localhost:4006/odata/v4/school/Students(student_id='2001')
Content-Type: application/json

 {
    "student_name": "BINDU"
}


###
DELETE http://localhost:4006/odata/v4/school/Students(student_id='2001')